SET(ANTLR3_SEARCH_FILENAME ${CMAKE_CURRENT_SOURCE_DIR}/antlr-3.jar)

IF (EXISTS ${ANTLR3_SEARCH_FILENAME})
  SET(ANTLR3_JAR ${ANTLR3_SEARCH_FILENAME})
ENDIF(EXISTS ${ANTLR3_SEARCH_FILENAME})

MACRO(ADD_ANTLR3_GRAMMAR GRAMMAR_NAME)
  SET(GrammarFile 
    ${CMAKE_CURRENT_SOURCE_DIR}/${GRAMMAR_NAME}.g)

  SET(ParserCFile 
    ${CMAKE_CURRENT_SOURCE_DIR}/${GRAMMAR_NAME}Parser.c)
  SET(ParserHFile 
    ${CMAKE_CURRENT_SOURCE_DIR}/${GRAMMAR_NAME}Parser.h)
    
  SET(LexerHFile 
    ${CMAKE_CURRENT_SOURCE_DIR}/${GRAMMAR_NAME}Lexer.h)  
  SET(LexerCFile 
    ${CMAKE_CURRENT_SOURCE_DIR}/${GRAMMAR_NAME}Lexer.c)

  IF(WIN32)
    ADD_CUSTOM_COMMAND(
      OUTPUT ${ParserCFile}
      COMMAND java ARGS -jar ${ANTLR3_JAR} -o ${GrammarFile}
      MAIN_DEPENDENCY ${GrammarFile})
  ELSE(WIN32)
    ADD_CUSTOM_COMMAND(
      OUTPUT ${ParserCFile}      
      COMMAND antlr3 ARGS ${GrammarFile}
      MAIN_DEPENDENCY ${GrammarFile})
  ENDIF(WIN32) 
  
  ADD_CUSTOM_COMMAND(OUTPUT ${ParserHFile}    
    COMMAND echo 
    DEPENDS ${ParserCFile})
    
  ADD_CUSTOM_COMMAND(OUTPUT ${LexerHFile}
    COMMAND echo
    DEPENDS ${ParserCFile})
  
  ADD_CUSTOM_COMMAND(OUTPUT ${LexerCFile}
    COMMAND echo
    DEPENDS ${ParserCFile})
  
  ADD_CUSTOM_TARGET(${GRAMMAR_NAME}Parser.c ALL DEPENDS ${ParserCFile})
ENDMACRO(ADD_ANTLR3_GRAMMAR)
