SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}")

MACRO(UD_FIND_LIB name header libname incs_var_name libs_var_name)
  IF (NOT UD_EMBED)
    FIND_PATH(${incs_var_name} ${header}
      ${CMAKE_CURRENT_SOURCE_DIR}/Ud/src/ud
      /usr/include
      /usr/local/include)
    FIND_LIBRARY(${libs_var_name}
      NAMES ${libname}
      PATHS /usr/lib/)
    IF(NOT ${incs_var_name} OR NOT ${libs_var_name})
      MESSAGE(FATAL_ERROR "Could not find " ${name})
    ENDIF(NOT ${incs_var_name} OR NOT ${libs_var_name})
  ELSE(NOT UD_EMBED)
    SET(${incs_var_name} "")
    SET(${libs_var_name} "")
  ENDIF(NOT UD_EMBED)
ENDMACRO(UD_FIND_LIB)

#SET(Boost_USE_STATIC_LIBS   ON)
SET(Boost_USE_MULTITHREADED ON)

IF(UD_COMMON)
  UD_FIND_LIB(UdCommon ud/common.hpp UdCommon
    UD_COMMON_INCLUDE_DIRS UD_COMMON_LIBRARIES)

  FIND_PACKAGE(OpenGL REQUIRED)
  FIND_PACKAGE(GLEW REQUIRED)
  FIND_PACKAGE(Boost REQUIRED COMPONENTS thread)

  SET(UD_COMMON_INCLUDE_DIRS
    ${UD_COMMON_INCLUDE_DIRS}
    ${OPENGL_INCLUDE_DIRS}
    ${Boost_INCLUDE_DIRS}
    ${GLEW_INCLUDE_DIRS})

  SET(UD_COMMON_LIBRARIES
    ${UD_COMMON_LIBRARIES}
    ${OPENGL_LIBRARIES}
    ${GLEW_LIBRARY}
    ${Boost_LIBRARIES})

  SET(UD_COMMON_LIBRARY_DIRS "")

  SET(UD_INCLUDE_DIRS ${UD_INCLUDE_DIRS} ${UD_COMMON_INCLUDE_DIRS})
  SET(UD_LIBRARIES ${UD_LIBRARIES} ${UD_COMMON_LIBRARIES})
  SET(UD_LIBRARY_DIRS ${UD_LIBRARY_DIRS} ${UD_COMMON_LIBRARY_DIRS})
ENDIF(UD_COMMON)

IF(UD_MATH)
  UD_FIND_LIB(UdMath ud/math/math.hpp UdMath
    UD_MATH_INCLUDE_DIRS UD_MATH_LIBRARIES)

  SET(UD_MATH_INCLUDE_DIRS ${UD_MATH_INCLUDE_DIRS})
  SET(UD_MATH_LIBRARIES ${UD_MATH_LIBRARIES})
  SET(UD_MATH_LIBRARY_DIRS "")

  SET(UD_INCLUDE_DIRS ${UD_INCLUDE_DIRS} ${UD_MATH_INCLUDE_DIRS})
  SET(UD_LIBRARIES ${UD_MATH_LIBRARIES} ${UD_LIBRARIES})
  SET(UD_LIBRARY_DIRS ${UD_LIBRARY_DIRS} ${UD_MATH_LIBRARY_DIRS})
ENDIF(UD_MATH)

IF(UD_UGL)
  UD_FIND_LIB(UdMesh ud/ugl/camera.hpp UdUgl
    UD_UGL_INCLUDE_DIRS UD_UGL_LIBRARIES)

  FIND_PACKAGE(SDL REQUIRED)
  SET(UD_UGL_INCLUDE_DIRS
    ${UD_UGL_INCLUDE_DIRS}
    ${SDL_INCLUDE_DIR})

  SET(UD_UGL_LIBRARIES
    ${UD_UGL_LIBRARIES}
    ${SDL_LIBRARY})

  SET(UD_UGL_LIBRARY_DIRS "")

  SET(UD_INCLUDE_DIRS ${UD_INCLUDE_DIRS} ${UD_UGL_INCLUDE_DIRS})
  SET(UD_LIBRARIES ${UD_UGL_LIBRARIES} ${UD_LIBRARIES})
  SET(UD_LIBRARY_DIRS ${UD_LIBRARY_DIRS} ${UD_UGL_LIBRARY_DIRS})
ENDIF(UD_UGL)

IF(UD_RES)
  UD_FIND_LIB(UdRes ud/res/mesh.hpp UdRes
    UD_RES_INCLUDE_DIRS UD_RES_LIBRARIES)

  FIND_PACKAGE(TBB REQUIRED)
  FIND_PACKAGE(FTGL REQUIRED)

  FIND_PACKAGE(Boost REQUIRED COMPONENTS filesystem system program_options)
  FIND_PACKAGE(GLUT REQUIRED)
  FIND_PACKAGE(DevIL REQUIRED)
  FIND_PACKAGE(Freetype REQUIRED)

  SET(UD_RES_INCLUDE_DIRS
    ${UD_RES_INCLUDE_DIRS}
    ${IL_INCLUDE_DIRS}
    ${FREETYPE_INCLUDE_DIRS}
    ${Boost_INCLUDE_DIRS}
    ${TBB_INCLUDE_DIRS})

  SET(UD_RES_LIBRARIES
    ${UD_RES_LIBRARIES}
    ${Boost_LIBRARIES}
    ${TBB_LIBRARIES}
    ${IL_LIBRARY}
    ${ILU_LIBRARY}
    ${ILUT_LIBRARY}
    ${FTGL_LIBRARY}
    ${FREETYPE_LIBRARIES})

  SET(UD_RES_LIBRARY_DIRS ${Boost_LIBRARY_DIRS} ${TBB_LIBRARY_DIRS})
  SET(UD_INCLUDE_DIRS ${UD_INCLUDE_DIRS} ${UD_RES_INCLUDE_DIRS})
  SET(UD_LIBRARIES ${UD_RES_LIBRARIES} ${UD_LIBRARIES})
  SET(UD_LIBRARY_DIRS ${UD_LIBRARY_DIRS} ${UD_RES_LIBRARY_DIRS})
ENDIF(UD_RES)

IF(UD_APP)
  UD_FIND_LIB(UdApp ud/app/application.hpp UdApp
    UD_APP_INCLUDE_DIRS UD_APP_LIBRARIES)

  SET(UD_APP_LIBRARY_DIRS "")

  SET(UD_INCLUDE_DIRS ${UD_INCLUDE_DIRS} ${UD_APP_INCLUDE_DIRS})
  SET(UD_LIBRARIES ${UD_APP_LIBRARIES} ${UD_LIBRARIES} )
  SET(UD_LIBRARY_DIRS ${UD_LIBRARY_DIRS} ${UD_APP_LIBRARY_DIRS})
ENDIF(UD_APP)

IF(UD_SCENE)
  UD_FIND_LIB(UdScene ud/scene/scene.hpp UdScene
    UD_SCENE_INCLUDE_DIRS UD_SCENE_LIBRARIES)

  SET(UD_SCENE_INCLUDE_DIRS ${UD_SCENE_INCLUDE_DIRS})
  SET(UD_SCENE_LIBRARIES ${UD_SCENE_LIBRARIES})
  SET(UD_SCENE_LIBRARY_DIRS "")

  SET(UD_INCLUDE_DIRS ${UD_INCLUDE_DIRS} ${UD_SCENE_INCLUDE_DIRS})
  SET(UD_LIBRARIES ${UD_SCENE_LIBRARIES} ${UD_LIBRARIES})
  SET(UD_LIBRARY_DIRS ${UD_LIBRARY_DIRS} ${UD_SCENE_LIBRARY_DIRS})
ENDIF(UD_SCENE)